#!/usr/bin/env python
import satelliz_agent_api

version = '1.0.0'

import os,time,sys

def check_age(file):
	st=os.stat(file)
	age=(time.time()-st.st_mtime)
	return age

def main(config):
	meta = {'file_age': {'limits': 1}}
	for x in xrange(1,9): 
		f = config.get("param%d" % x)
		if not f:
			continue
		try:
			age = check_age(f)
			perfdata = {'file_age': age}
			satelliz_agent_api.add_metric('File%d' % x, 0, perfdata, "%s is %.1f seconds old" % (f, age), meta)
		except OSError, e:
			satelliz_agent_api.add_metric('File%d' % x, 2, {}, "Problem checking %s age: %s" % (f, e))
		except Exception, e:
			satelliz_agent_api.add_metric('File%d' % x, 2, {}, "Problem checking %s age: %r" % (f, e))

